/**
 * Migration 003: Fix missing columns that cause fetch failures
 * Adds: deleted_at, is_manually_edited, manual_fields, source_url, external_id, content_hash
 * Also adds: triggered_by column to fetch_logs if missing
 */

function runMigration(pgdb) {
  console.log('[Migration 003] Checking for missing columns...');

  const alterStatements = [
    // news table columns
    `DO $$ BEGIN
      BEGIN ALTER TABLE news ADD COLUMN deleted_at TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END;
      BEGIN ALTER TABLE news ADD COLUMN is_manually_edited INTEGER DEFAULT 0; EXCEPTION WHEN duplicate_column THEN NULL; END;
      BEGIN ALTER TABLE news ADD COLUMN manual_fields TEXT DEFAULT ''; EXCEPTION WHEN duplicate_column THEN NULL; END;
      BEGIN ALTER TABLE news ADD COLUMN source_url TEXT; EXCEPTION WHEN duplicate_column THEN NULL; END;
      BEGIN ALTER TABLE news ADD COLUMN external_id TEXT; EXCEPTION WHEN duplicate_column THEN NULL; END;
      BEGIN ALTER TABLE news ADD COLUMN content_hash TEXT; EXCEPTION WHEN duplicate_column THEN NULL; END;
    END $$`,

    // fetch_logs table - add triggered_by if missing
    `DO $$ BEGIN
      BEGIN ALTER TABLE fetch_logs ADD COLUMN triggered_by TEXT DEFAULT 'unknown'; EXCEPTION WHEN duplicate_column THEN NULL; END;
    END $$`,

    // Create indexes if missing
    'CREATE INDEX IF NOT EXISTS idx_news_deleted ON news(deleted_at)',
    'CREATE INDEX IF NOT EXISTS idx_news_manually_edited ON news(is_manually_edited)',
    'CREATE INDEX IF NOT EXISTS idx_news_content_hash ON news(content_hash)',
    'CREATE INDEX IF NOT EXISTS idx_news_source_url ON news(source_url)',
    'CREATE INDEX IF NOT EXISTS idx_fetch_logs_triggered ON fetch_logs(triggered_by)',
    'CREATE INDEX IF NOT EXISTS idx_fetch_logs_started ON fetch_logs(started_at)',

    // Create deleted_articles table if missing
    `CREATE TABLE IF NOT EXISTS deleted_articles (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      original_id BIGINT,
      title TEXT NOT NULL,
      source_url TEXT,
      content_hash TEXT,
      deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      deleted_by TEXT DEFAULT 'admin'
    )`,
    'CREATE INDEX IF NOT EXISTS idx_deleted_articles_title ON deleted_articles(title)',
    'CREATE INDEX IF NOT EXISTS idx_deleted_articles_url ON deleted_articles(source_url)',
    'CREATE INDEX IF NOT EXISTS idx_deleted_articles_hash ON deleted_articles(content_hash)',

    // Create fetch_locks table if missing
    `CREATE TABLE IF NOT EXISTS fetch_locks (
      lock_name TEXT PRIMARY KEY,
      locked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      locked_by TEXT,
      expires_at TIMESTAMP NOT NULL
    )`,
    'CREATE INDEX IF NOT EXISTS idx_fetch_locks_expires ON fetch_locks(expires_at)',
  ];

  let success = 0;
  let errors = 0;

  for (const sql of alterStatements) {
    try {
      pgdb.exec(sql);
      success++;
    } catch (e) {
      // Log but don't fail - some statements may already exist
      console.log(`[Migration 003] Statement warning: ${e.message}`);
      errors++;
    }
  }

  // Verify columns exist
  try {
    const check = pgdb.prepare("SELECT column_name FROM information_schema.columns WHERE table_name = 'news' AND column_name IN ('deleted_at','content_hash','source_url','is_manually_edited')").all();
    const found = check.map(r => r.column_name);
    console.log(`[Migration 003] Verified news columns: ${found.join(', ')}`);

    const missing = ['deleted_at', 'content_hash', 'source_url', 'is_manually_edited'].filter(c => !found.includes(c));
    if (missing.length > 0) {
      console.error(`[Migration 003] CRITICAL: Still missing columns: ${missing.join(', ')}`);
    } else {
      console.log('[Migration 003] All critical columns present ✓');
    }
  } catch (e) {
    console.log(`[Migration 003] Verification skipped: ${e.message}`);
  }

  // Fix broken and disabled sources - activate reliable RSS feeds
  console.log('[Migration 003] Fixing news sources...');
  try {
    // Disable all currently broken/disabled sources
    pgdb.prepare("UPDATE news_sources SET is_active = 0, last_fetch_status = 'disabled' WHERE last_fetch_status = 'disabled' OR last_error LIKE '%not working%'").run();

    // Reliable RSS sources to ensure exist and are active
    const reliableSources = [
      { name: 'BBC Arabic', url: 'https://feeds.bbci.co.uk/arabic/rss.xml', type: 'rss', interval: 900 },
      { name: 'Al Jazeera', url: 'https://www.aljazeera.com/xml/rss/all.xml', type: 'rss', interval: 900 },
      { name: 'France 24 Arabic', url: 'https://www.france24.com/ar/rss', type: 'rss', interval: 1200 },
      { name: 'Sky News Arabia', url: 'https://www.skynewsarabia.com/rss', type: 'rss', interval: 1200 },
      { name: 'DW Arabic', url: 'https://rss.dw.com/xml/rss-arb', type: 'rss', interval: 1200 },
    ];

    // De-duplicate: keep only one active source per URL
    for (const src of reliableSources) {
      const existing = pgdb.prepare('SELECT id, is_active FROM news_sources WHERE url = ?').all(src.url);
      if (existing.length > 1) {
        // Keep the first one, disable the rest
        for (let i = 1; i < existing.length; i++) {
          pgdb.prepare('UPDATE news_sources SET is_active = 0 WHERE id = ?').run(existing[i].id);
        }
      }
      if (existing.length >= 1) {
        // Activate and reset the first one
        pgdb.prepare("UPDATE news_sources SET name = ?, source_type = ?, is_active = 1, last_fetch_status = 'pending', last_error = NULL, fetch_interval = ?, next_fetch_at = CURRENT_TIMESTAMP WHERE id = ?").run(src.name, src.type, src.interval, existing[0].id);
      } else {
        // Insert new
        pgdb.prepare('INSERT INTO news_sources (name, url, source_type, is_active, fetch_interval, auto_publish, next_fetch_at, last_fetch_status) VALUES (?, ?, ?, 1, ?, 1, CURRENT_TIMESTAMP, ?)').run(src.name, src.url, src.type, src.interval, 'pending');
      }
    }

    // Disable Al Jazeera Arabic (522 error) if it's still failing
    pgdb.prepare("UPDATE news_sources SET is_active = 0, last_fetch_status = 'disabled', last_error = 'Status code 522 - blocked' WHERE url = 'https://www.aljazeera.net/rss'").run();

    // Final count
    const activeCount = pgdb.prepare('SELECT COUNT(*) as cnt FROM news_sources WHERE is_active = 1').get();
    console.log(`[Migration 003] Active sources after fix: ${activeCount.cnt}`);
  } catch (e) {
    console.log(`[Migration 003] Source fix error: ${e.message}`);
  }

  console.log(`[Migration 003] Completed: ${success} OK, ${errors} warnings`);
}

module.exports = { runMigration };
