const API='https://uwyjpykfpyusnbvtrfjh.supabase.co/functions/v1/awtar-api';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const img=u=>{if(!u)return '/images/placeholder.jpg';if(/^https?:\/\//i.test(u))return `${API}/image?url=${encodeURIComponent(u)}`;return u.startsWith('/')?u:'/images/placeholder.jpg'};
async function get(path){const r=await fetch(API+path);if(!r.ok)throw Error('تعذر تحميل البيانات');return r.json()}
function header(categories=[]){return `<div class="top"><div class="shell"><span>أوتر نيوز | الخبر كما هو</span><span>${new Date().toLocaleDateString('ar-YE')}</span></div></div><header class="mast"><div class="shell"><a class="brand" href="/"><img src="/images/logo.png"><span><strong>أوتر نيوز</strong><small>المصدر الأول للأخبار المحلية والعربية والعالمية</small></span></a></div></header><nav class="nav"><div class="shell"><a href="/">الرئيسية</a>${categories.slice(0,10).map(c=>`<a href="/?category=${c.id}">${esc(c.name_ar)}</a>`).join('')}<a href="/?search=">بحث</a></div></nav>`}
function footer(){return `<footer class="footer"><div class="shell"><b>أوتر نيوز</b><p>منصة إخبارية عربية مستقلة، تعمل الآن على Firebase Hosting وSupabase.</p><small>© ${new Date().getFullYear()} Awtar News</small></div></footer>`}
function card(n){return `<article class="card"><a href="/news/${n.id}"><img loading="lazy" src="${esc(img(n.image))}" alt=""><div class="card-body"><div class="meta">${esc(n.source||'أوتر نيوز')} · ${n.published_at?new Date(n.published_at).toLocaleDateString('ar-YE'):''}</div><h3>${esc(n.title)}</h3><p class="meta">${esc((n.summary||n.content||'').slice(0,130))}</p></div></a></article>`}
async function home(){const params=new URLSearchParams(location.search);const q=params.get('search');const cat=params.get('category');const [cats,news]=await Promise.all([get('/categories'),get(`/news?limit=30${q?`&q=${encodeURIComponent(q)}`:''}${cat?`&category=${cat}`:''}`)]);const lead=news[0];document.title=q?`بحث: ${q} | أوتر نيوز`:'أوتر نيوز';document.getElementById('app').innerHTML=header(cats)+`<main class="shell hero"><div class="ticker"><b>عاجل</b><span>${esc(news.find(n=>n.is_breaking)?.title||'تابع آخر الأخبار والتطورات')}</span></div>${q?`<div class="section-title"><h2>نتائج البحث عن: ${esc(q)}</h2></div>`:''}<div class="search"><input id="q" value="${esc(q||'')}" placeholder="ابحث في الأخبار"><button onclick="doSearch()">بحث</button></div>${lead&&!q&&!cat?`<section class="lead" style="margin-top:18px"><article class="lead-card"><a href="/news/${lead.id}"><img src="${esc(img(lead.image))}" alt=""><div class="lead-body"><div class="meta">${esc(lead.source||'أوتر نيوز')}</div><h1>${esc(lead.title)}</h1><p>${esc(lead.summary||'')}</p></div></a></article><div class="grid" style="grid-template-columns:1fr 1fr">${news.slice(1,5).map(card).join('')}</div></section>`:''}<div class="section-title"><h2>${q||cat?'الأخبار':'أحدث الأخبار'}</h2><a href="/?search=">كل الأخبار</a></div><section class="grid">${news.length?news.map(card).join(''):'<div class="empty">لا توجد أخبار مطابقة.</div>'}</section></main>${footer()}`}
async function article(id){const [cats,n]=await Promise.all([get('/categories'),get('/news/'+id)]);if(!n){location.href='/';return}document.title=n.title;document.getElementById('app').innerHTML=header(cats)+`<main class="shell"><article class="article"><div class="meta">${esc(n.source||'أوتر نيوز')} · ${n.published_at?new Date(n.published_at).toLocaleDateString('ar-YE'):''}</div><h1>${esc(n.title)}</h1>${n.image?`<img src="${esc(img(n.image))}" alt="">`:''}<p>${esc(n.summary||'')}</p><div class="content">${esc(n.content||'')}</div></article></main>${footer()}`}
function doSearch(){const q=document.getElementById('q').value.trim();location.href=q?`/?search=${encodeURIComponent(q)}`:'/'}
(async()=>{try{const m=location.pathname.match(/^\/news\/(\d+)/);await(m?article(m[1]):home())}catch(e){document.getElementById('app').innerHTML='<div class="shell empty">تعذر تحميل الموقع مؤقتًا. حاول تحديث الصفحة.</div>'}})();
