const fs = require('fs');
const path = require('path');
const os = require('os');
const crypto = require('crypto');
const { Worker } = require('worker_threads');
const { seedData } = require('./seed-data');

let db = null;
let initialized = false;
let worker = null;
let queryCounter = 0;

function ensureWorker() {
  if (!worker) {
    worker = new Worker(path.join(__dirname, 'pg-worker.js'), {
      env: process.env
    });
  }
  return worker;
}

function querySync(sql, params = []) {
  ensureWorker();
  const signalBuffer = new SharedArrayBuffer(4);
  const signal = new Int32Array(signalBuffer);
  const payloadPath = path.join(os.tmpdir(), `pgsync-${process.pid}-${Date.now()}-${++queryCounter}-${crypto.randomBytes(4).toString('hex')}.json`);

  worker.postMessage({ sql, params, signalBuffer, payloadPath });

  const waitResult = Atomics.wait(signal, 0, 0, 300000);
  if (waitResult === 'timed-out') {
    throw new Error('PostgreSQL query timed out');
  }

  const raw = fs.readFileSync(payloadPath, 'utf8');
  fs.unlinkSync(payloadPath);
  const parsed = JSON.parse(raw);

  if (!parsed.ok) {
    const err = new Error(parsed.error?.message || 'PostgreSQL query failed');
    if (parsed.error) Object.assign(err, parsed.error);
    throw err;
  }

  return parsed;
}

function replacePlaceholders(sql) {
  let index = 0;
  return sql.replace(/\?/g, () => `$${++index}`);
}

function normalizeSql(sql) {
  let normalized = String(sql || '').trim();

  normalized = normalized.replace(/datetime\('now',\s*'-1 hour'\)/gi, "NOW() - INTERVAL '1 hour'");
  normalized = normalized.replace(/datetime\("now",\s*'-1 hour'\)/gi, "NOW() - INTERVAL '1 hour'");

  if (/^INSERT\s+OR\s+IGNORE\s+INTO\s+/i.test(normalized)) {
    normalized = normalized.replace(/^INSERT\s+OR\s+IGNORE\s+INTO\s+/i, 'INSERT INTO ');
    normalized += ' ON CONFLICT DO NOTHING';
  } else if (/^INSERT\s+OR\s+REPLACE\s+INTO\s+/i.test(normalized)) {
    const match = normalized.match(/^INSERT\s+OR\s+REPLACE\s+INTO\s+([^(\s]+)\s*\(([^)]+)\)\s*VALUES\s*\(([^)]+)\)$/i);
    if (match) {
      const table = match[1];
      const columns = match[2].split(',').map((c) => c.trim());
      const values = match[3];
      const conflictTarget = columns[0];
      const updates = columns.slice(1).map((c) => `${c} = EXCLUDED.${c}`).join(', ');
      normalized = `INSERT INTO ${table} (${columns.join(', ')}) VALUES (${values}) ON CONFLICT (${conflictTarget}) DO UPDATE SET ${updates}`;
    } else {
      normalized = normalized.replace(/^INSERT\s+OR\s+REPLACE\s+INTO\s+/i, 'INSERT INTO ');
    }
  }

  return replacePlaceholders(normalized);
}

class PgStatement {
  constructor(sql) {
    this.sql = sql;
  }

  get(...params) {
    const result = querySync(normalizeSql(this.sql), params);
    return result.rows[0];
  }

  all(...params) {
    const result = querySync(normalizeSql(this.sql), params);
    return result.rows;
  }

  run(...params) {
    let sql = normalizeSql(this.sql);
    if (/^INSERT\s+INTO\s+/i.test(sql) && !/\bRETURNING\b/i.test(sql)) {
      sql += ' RETURNING *';
    }
    const result = querySync(sql, params);
    const firstRow = result.rows && result.rows[0] ? result.rows[0] : null;
    return {
      changes: result.rowCount || 0,
      lastInsertRowid: firstRow && Object.prototype.hasOwnProperty.call(firstRow, 'id') ? firstRow.id : null
    };
  }
}

class PgCompatDatabase {
  prepare(sql) {
    return new PgStatement(sql);
  }

  exec(sql) {
    const statements = String(sql)
      .split(';')
      .map((s) => s.trim())
      .filter(Boolean);

    for (const statement of statements) {
      querySync(statement, []);
    }
  }

  pragma() {
    return null;
  }
}

function getDb() {
  if (!db) {
    db = new PgCompatDatabase();
  }
  return db;
}

function createSchema(pgdb) {
  const statements = [
    `CREATE TABLE IF NOT EXISTS categories (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name_ar TEXT NOT NULL,
      name_en TEXT,
      slug TEXT UNIQUE,
      sort_order INTEGER DEFAULT 0,
      is_active INTEGER DEFAULT 1
    )`,
    `CREATE TABLE IF NOT EXISTS news (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      summary TEXT,
      content TEXT,
      image TEXT,
      category_id BIGINT,
      source TEXT,
      is_breaking INTEGER DEFAULT 0,
      is_slider INTEGER DEFAULT 0,
      is_featured INTEGER DEFAULT 0,
      views INTEGER DEFAULT 0,
      status INTEGER DEFAULT 1,
      published_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      meta_title TEXT,
      meta_description TEXT,
      slug TEXT,
      CONSTRAINT fk_news_category FOREIGN KEY (category_id) REFERENCES categories(id)
    )`,
    `CREATE TABLE IF NOT EXISTS tags (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      slug TEXT UNIQUE
    )`,
    `CREATE TABLE IF NOT EXISTS news_tags (
      news_id BIGINT,
      tag_id BIGINT,
      PRIMARY KEY (news_id, tag_id),
      CONSTRAINT fk_news_tags_news FOREIGN KEY (news_id) REFERENCES news(id) ON DELETE CASCADE,
      CONSTRAINT fk_news_tags_tag FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS media (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      type TEXT NOT NULL,
      title TEXT,
      file_path TEXT NOT NULL,
      thumbnail TEXT,
      description TEXT,
      category TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS breaking_news (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      text TEXT NOT NULL,
      link TEXT,
      is_active INTEGER DEFAULT 1,
      sort_order INTEGER DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS slider (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      news_id BIGINT,
      image TEXT,
      title TEXT,
      summary TEXT,
      link TEXT,
      sort_order INTEGER DEFAULT 0,
      is_active INTEGER DEFAULT 1,
      CONSTRAINT fk_slider_news FOREIGN KEY (news_id) REFERENCES news(id)
    )`,
    `CREATE TABLE IF NOT EXISTS advertisements (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      position TEXT,
      code TEXT,
      image TEXT,
      link TEXT,
      start_date DATE,
      end_date DATE,
      is_active INTEGER DEFAULT 1
    )`,
    `CREATE TABLE IF NOT EXISTS admin_users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username TEXT UNIQUE NOT NULL,
      password TEXT NOT NULL,
      name TEXT,
      role TEXT DEFAULT 'editor',
      last_login TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS settings (
      key TEXT PRIMARY KEY,
      value TEXT
    )`,
    `CREATE TABLE IF NOT EXISTS comments (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      news_id BIGINT NOT NULL,
      author_name TEXT NOT NULL,
      author_email TEXT,
      content TEXT NOT NULL,
      status INTEGER DEFAULT 0,
      ip_address TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT fk_comments_news FOREIGN KEY (news_id) REFERENCES news(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS polls (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      question TEXT NOT NULL,
      is_active INTEGER DEFAULT 1,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      expires_at TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS poll_options (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      poll_id BIGINT NOT NULL,
      option_text TEXT NOT NULL,
      votes INTEGER DEFAULT 0,
      CONSTRAINT fk_poll_options_poll FOREIGN KEY (poll_id) REFERENCES polls(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS poll_votes (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      poll_id BIGINT NOT NULL,
      option_id BIGINT NOT NULL,
      ip_address TEXT NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT fk_poll_votes_poll FOREIGN KEY (poll_id) REFERENCES polls(id) ON DELETE CASCADE,
      CONSTRAINT fk_poll_votes_option FOREIGN KEY (option_id) REFERENCES poll_options(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS newsletter_subscribers (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email TEXT UNIQUE NOT NULL,
      name TEXT,
      is_active INTEGER DEFAULT 1,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      unsubscribed_at TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS newsletter_campaigns (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      subject TEXT NOT NULL,
      content TEXT NOT NULL,
      sent_at TIMESTAMP,
      recipients_count INTEGER DEFAULT 0,
      status INTEGER DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS images (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      filename TEXT NOT NULL,
      mime_type TEXT NOT NULL,
      data TEXT NOT NULL,
      size INTEGER DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS news_sources (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      url TEXT NOT NULL,
      source_type TEXT DEFAULT 'auto',
      category_id BIGINT,
      is_active INTEGER DEFAULT 1,
      fetch_interval INTEGER DEFAULT 900,
      last_fetched_at TIMESTAMP,
      next_fetch_at TIMESTAMP,
      last_fetch_status TEXT DEFAULT 'pending',
      last_error TEXT,
      total_fetched INTEGER DEFAULT 0,
      total_duplicates INTEGER DEFAULT 0,
      last_new_count INTEGER DEFAULT 0,
      use_proxy INTEGER DEFAULT 0,
      proxy_url TEXT,
      auto_publish INTEGER DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT fk_source_category FOREIGN KEY (category_id) REFERENCES categories(id)
    )`,
    `CREATE TABLE IF NOT EXISTS fetch_logs (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      source_id BIGINT NOT NULL,
      started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      finished_at TIMESTAMP,
      status TEXT DEFAULT 'running',
      new_count INTEGER DEFAULT 0,
      duplicate_count INTEGER DEFAULT 0,
      image_count INTEGER DEFAULT 0,
      triggered_by TEXT DEFAULT 'unknown',
      error_message TEXT,
      details TEXT,
      CONSTRAINT fk_log_source FOREIGN KEY (source_id) REFERENCES news_sources(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS deleted_articles (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      original_id BIGINT,
      title TEXT NOT NULL,
      source_url TEXT,
      content_hash TEXT,
      deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      deleted_by TEXT DEFAULT 'admin'
    )`,
    'CREATE INDEX IF NOT EXISTS idx_deleted_articles_title ON deleted_articles(title)',
    'CREATE INDEX IF NOT EXISTS idx_deleted_articles_url ON deleted_articles(source_url)',
    'CREATE INDEX IF NOT EXISTS idx_deleted_articles_hash ON deleted_articles(content_hash)',
    // Soft delete + field-level manual edit protection + fingerprinting
    `DO $$ BEGIN
      BEGIN ALTER TABLE news ADD COLUMN deleted_at TIMESTAMP; EXCEPTION WHEN duplicate_column THEN NULL; END;
      BEGIN ALTER TABLE news ADD COLUMN is_manually_edited INTEGER DEFAULT 0; EXCEPTION WHEN duplicate_column THEN NULL; END;
      BEGIN ALTER TABLE news ADD COLUMN manual_fields TEXT DEFAULT ''; EXCEPTION WHEN duplicate_column THEN NULL; END;
      BEGIN ALTER TABLE news ADD COLUMN source_url TEXT; EXCEPTION WHEN duplicate_column THEN NULL; END;
      BEGIN ALTER TABLE news ADD COLUMN external_id TEXT; EXCEPTION WHEN duplicate_column THEN NULL; END;
      BEGIN ALTER TABLE news ADD COLUMN content_hash TEXT; EXCEPTION WHEN duplicate_column THEN NULL; END;
    END $$`,
    'CREATE INDEX IF NOT EXISTS idx_news_deleted ON news(deleted_at)',
    'CREATE INDEX IF NOT EXISTS idx_news_manually_edited ON news(is_manually_edited)',
    'CREATE INDEX IF NOT EXISTS idx_news_content_hash ON news(content_hash)',
    'CREATE INDEX IF NOT EXISTS idx_news_source_url ON news(source_url)',
    `CREATE TABLE IF NOT EXISTS fetch_locks (
      lock_name TEXT PRIMARY KEY,
      locked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      locked_by TEXT,
      expires_at TIMESTAMP NOT NULL
    )`,
    'CREATE INDEX IF NOT EXISTS idx_news_category ON news(category_id)',
    'CREATE INDEX IF NOT EXISTS idx_news_status ON news(status)',
    'CREATE INDEX IF NOT EXISTS idx_news_published ON news(published_at)',
    'CREATE INDEX IF NOT EXISTS idx_news_breaking ON news(is_breaking)',
    'CREATE INDEX IF NOT EXISTS idx_news_slider ON news(is_slider)',
    'CREATE INDEX IF NOT EXISTS idx_news_featured ON news(is_featured)',
    'CREATE INDEX IF NOT EXISTS idx_comments_news ON comments(news_id)',
    'CREATE INDEX IF NOT EXISTS idx_comments_status ON comments(status)',
    'CREATE INDEX IF NOT EXISTS idx_poll_votes_poll ON poll_votes(poll_id, ip_address)',
    'CREATE INDEX IF NOT EXISTS idx_newsletter_email ON newsletter_subscribers(email)',
    'CREATE INDEX IF NOT EXISTS idx_fetch_locks_expires ON fetch_locks(expires_at)',
    'CREATE INDEX IF NOT EXISTS idx_fetch_logs_triggered ON fetch_logs(triggered_by)',
    'CREATE INDEX IF NOT EXISTS idx_fetch_logs_started ON fetch_logs(started_at)',
    `CREATE TABLE IF NOT EXISTS audit_log (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      admin_user TEXT,
      action TEXT NOT NULL,
      entity_type TEXT,
      entity_id BIGINT,
      old_values TEXT,
      new_values TEXT,
      ip_address TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    'CREATE INDEX IF NOT EXISTS idx_audit_log_action ON audit_log(action)',
    'CREATE INDEX IF NOT EXISTS idx_audit_log_entity ON audit_log(entity_type, entity_id)',
    'CREATE INDEX IF NOT EXISTS idx_audit_log_created ON audit_log(created_at)'
  ];

  for (const sql of statements) {
    pgdb.exec(sql);
  }
}

function seedPostgres(pgdb) {
  seedData(pgdb);

  const sequenceTables = [
    'categories', 'tags', 'news', 'media', 'breaking_news', 'slider',
    'advertisements', 'admin_users', 'comments', 'polls', 'poll_options',
    'poll_votes', 'newsletter_subscribers', 'newsletter_campaigns', 'images',
    'news_sources', 'fetch_logs', 'deleted_articles', 'audit_log'
  ];

  for (const table of sequenceTables) {
    try {
      pgdb.exec(`SELECT setval(pg_get_serial_sequence('${table}', 'id'), COALESCE((SELECT MAX(id) FROM ${table}), 1), true)`);
    } catch(e) {}
  }

  // Auto-add working RSS sources if none exist
  try {
    const sourceCount = pgdb.prepare('SELECT COUNT(*) as cnt FROM news_sources').get();
    if (!sourceCount || sourceCount.cnt === 0) {
      console.log('No news sources found, adding default sources...');
      const defaultSources = [
        ['BBC Arabic', 'https://feeds.bbci.co.uk/arabic/rss.xml', 'rss', 2, 900, 1],
        ['Al Jazeera', 'https://www.aljazeera.com/xml/rss/all.xml', 'rss', 2, 900, 1],
        ['France 24 Arabic', 'https://www.francetvinfo.fr/titres.rss', 'rss', 2, 1200, 1],
        ['Reuters Arabic', 'https://www.reutersagency.com/feed/', 'rss', 2, 1200, 1],
        ['Sky News Arabia', 'https://www.skynewsarabia.com/web/rss.xml', 'rss', 2, 1200, 1]
      ];
      const insertSource = pgdb.prepare('INSERT INTO news_sources (name, url, source_type, category_id, fetch_interval, auto_publish, next_fetch_at, last_fetch_status) VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?)');
      for (const [name, url, type, catId, interval, autoPub] of defaultSources) {
        try {
          insertSource.run(name, url, type, catId, interval, autoPub, 'pending');
        } catch(e) { console.log('Source add error:', name, e.message); }
      }
    }
  } catch(e) { console.log('Source check error:', e.message); }
}

function initDatabase() {
  if (initialized) return;

  const pgdb = getDb();
  createSchema(pgdb);

  const count = pgdb.prepare('SELECT COUNT(*) as cnt FROM categories').get();
  if (!count || !count.cnt) {
    seedPostgres(pgdb);
  }

  // Run migrations
  try {
    const sourceCount = pgdb.prepare('SELECT COUNT(*) as cnt FROM news_sources WHERE is_active = 1').get();
    if (sourceCount && sourceCount.cnt > 0) {
      // Check if sources have broken URLs
      const brokenSources = pgdb.prepare("SELECT id, name, url FROM news_sources WHERE url LIKE '%saba.ye%' OR url LIKE '%almassirah.net%' OR url LIKE '%alarabiya.net%' OR url LIKE '%maribpress.net%' OR url LIKE '%newyemen.net%'").all();
      if (brokenSources.length > 0) {
        console.log(`Found ${brokenSources.length} broken sources, fixing...`);
        // Update broken sources to working URLs
        const fixes = [
          { url: '%saba.ye%', name: 'BBC Arabic RSS', newUrl: 'https://feeds.bbci.co.uk/arabic/rss.xml' },
          { url: '%almassirah.net%', name: 'Al Jazeera RSS', newUrl: 'https://www.aljazeera.com/xml/rss/all.xml' },
          { url: '%alarabiya.net%', name: 'France 24 RSS', newUrl: 'https://www.francetvinfo.fr/titres.rss' },
          { url: '%maribpress.net%', name: 'Disabled - maribpress', newUrl: null },
          { url: '%newyemen.net%', name: 'Disabled - newyemen', newUrl: null }
        ];
        for (const fix of fixes) {
          if (fix.newUrl) {
            pgdb.prepare("UPDATE news_sources SET name = ?, url = ?, last_fetch_status = 'pending', last_error = NULL WHERE url LIKE ?").run(fix.name, fix.newUrl, fix.url);
          } else {
            pgdb.prepare("UPDATE news_sources SET is_active = 0, last_fetch_status = 'disabled' WHERE url LIKE ?").run(fix.url);
          }
        }
        console.log('Fixed broken sources');
      }
    }
  } catch(e) { console.log('Migration error:', e.message); }

  initialized = true;
}

module.exports = { getDb, initDatabase };
